services:
  
  frontend:

    build:
      context: ../web-frontend/FEM_FRONT/
      dockerfile: Dockerfile

    image: fem-frontend:1.0

    ports:
      - "8050:8050"

    depends_on:
      - gateway

    networks:
      - frontend

  gateway:

    build:
      context: ../python-backend/api_gateway/
      dockerfile: Dockerfile

    image: api-gateway:1.0

    environment:
      ATTENDANCE_SVC_URL: http://attendance:8000
      EVENT_SVC_URL: http://event_manager:8020
      LOGIN_SVC_URL: http://login:8070
      EMAIL_SVC_URL: http://kafka:8090
      FRONT_URL: http://frontend:8050
      REFRESH_TOKEN_COOKIE_NAME: "refreshToken"

    ports:
      - "8010:8010"

    networks:
      - backend
      - frontend

  attendance:

    build:
      context: ../python-backend/attendance/
      dockerfile: Dockerfile

    image: attendance:1.0

    environment:
      KAFKA_ADDRESS: "kafka:9092"

    ports:
      - "8000:8000"

    depends_on:
      kafka:
        condition: service_healthy

    networks:
      - mail
      - backend

  event_manager:

    build:
      context: ../python-backend/event_manager/
      dockerfile: Dockerfile

    image: event_manager:1.0

    ports:
      - "8020:8020"
    
    networks:
      - backend

  kafka:

    image: apache/kafka:3.7.0
    container_name: kafka
    
    ports:
      - "9092:9092"
    
    volumes:
      - ./kafka/config/server.properties:/opt/kafka/config/server.properties
      - kafka_data:/var/lib/kafka/data
    
    command:
      - sh
      - -c
      - >
          CLUSTER_ID=$$(/opt/kafka/bin/kafka-storage.sh random-uuid) &&
          /opt/kafka/bin/kafka-storage.sh format -t $$CLUSTER_ID -c /opt/kafka/config/server.properties &&
          /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties
    
    healthcheck:
      test: ["CMD", "bash", "-c", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    networks:
      - mail
      
  mysql:

    image: mysql:8.0
    container_name: auth_mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authdb

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
    
    networks:
      - auth

  login:

    build:
      context: ../java-backend/authentication/
      dockerfile: Dockerfile

    image: login-service:1.0

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/authdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      AUTH_PASSWORD: mysupersecretkey123
    ports:
      - "8070:8070"

    depends_on:
      kafka:
        condition: service_healthy
      mysql:
        condition: service_healthy

    networks:
      - auth
      - backend

  email:

    build:
      context: ../java-backend/email/
      dockerfile: Dockerfile

    image: email-service:1.0

    environment:
      KAFKA_ADDRESS: "kafka:9092"
      MAIL_PASSWORD: ${MAIL_PASSWORD}

    ports:
      - "8090:8090"

    depends_on:
      kafka:
        condition: service_healthy

    networks:
      - mail

volumes:
  kafka_data:
  mysql_data:

networks:
  mail:
  backend:
  auth:
  frontend:
