spring.application.name=authentication
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=root
spring.datasource.password=root

kafka.address=${KAFKA_ADDRESS}
email.topic=email.send

jwt.secret=${AUTH_PASSWORD}
jwt.expirySeconds=20000

logging.level.org.springframework.security=DEBUG
logging.level.com.example.auth=DEBUG
logging.level.org.hibernate.SQL=DEBUG


server.port=8070
